### ISSUE TITLE
Introduce jQuery dependency

### ISSUE THREAD

**Issue by chenglou** [bsansouci/split-thegame#1]
For DOM manipulations.

**Comment by chenglou** [comment]
@bsansouci really think we should handle the issue soon

**Comment by Schmavery** [comment]
Actually we're planning a rewrite using angular so this won't be necessary.

**Comment by chenglou** [comment]
Yo fuck off u know dis shit works me up u cant just troll ppl liek dat on internet

**Comment by chenglou** [comment]
Closing this to prevent excess trolling
